### ISSUE TITLE
「障害物を設置する杖」を導入すると全ユニットが敵対ユニットを通過可能になる

### ISSUE THREAD

**Issue by odama16020** [CordialBun/srpg-studio-plugin#32]
`SimulationBlockerControl._configureBlockerRule` 内の `isTargetBlocker` で、障害物以外を `false` としていることにより表題の事象が発生するようです。
公式プラグイン `simulation-levelfilter.js` にあるように、

```
if (!FilterControl.isReverseUnitTypeAllowed(unit, targetUnit)) {
	return false;
}
```

として敵対しないユニットのみ `false` を返し、それ以外は `true` を返す、といった処理にする必要がありそうです。
（テスト不十分なため、上記処理の追加のみで問題ないかは自信ないです）

**Comment by CordialBun** [comment]
報告ありがとうございます！
`FilterControl.isReverseUnitTypeAllowed(unit, targetUnit)`の判定を追加することで正常に動作することが確認できましたので、そのように修正しました。
